# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(1, 'PGY1'), (2, 'PGY2'), (3, 'PGY3'), (4, 'PGY4'), (5, 'PGY5')])),
                ('noCallDays', models.IntegerField()),
                ('noWkndCallDays', models.IntegerField()),
                ('resType', models.CharField(blank=True, max_length=16)),
                ('PTO', models.ManyToManyField(to='scheduler.DayOff')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('onservice', models.IntegerField(choices=[(1, 'Trauma'), (2, 'Hepatobiliary / Transplant'), (3, 'Vascular'), (4, 'Colorectal'), (5, 'Breast'), (6, 'Gen Surg - Gold'), (7, 'Gen Surg - Blue'), (8, 'Gen Surg - Orange'), (9, 'Plastics'), (10, 'PCH'), (11, 'Thoracic'), (12, 'Anesthesia / IR'), (13, 'Other')])),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Resident')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='residents',
            field=models.ManyToManyField(to='scheduler.Resident'),
        ),
    ]
