# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_resident_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='noCallDays',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='noWkndCallDays',
        ),
    ]
