# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20170726_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='residents',
            field=models.ManyToManyField(blank=True, to='scheduler.Resident', verbose_name='Residents on Call'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='year',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'PGY1'), (2, 'PGY2'), (3, 'PGY3'), (4, 'PGY4'), (5, 'PGY5')], verbose_name='Year of Service'),
        ),
    ]
